use rts::compute;
use argh::FromArgs;

#[derive(FromArgs)]
/// Parse Ruby controller folder and routes file to produce Swagger file
struct RtsCmd {
    /// directory of the controller ruby files
    #[argh(positional)]
    controller: String,

    /// routes file generated by running bundle exec rails routes
    #[argh(positional)]
    routes: String,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cmd: RtsCmd = argh::from_env();
    compute(
        &cmd.controller,
        &cmd.routes,
    )?;
    Ok(())
}
